[package]
name = "rustsetup2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "46.0.0"
datafusion = "30.0.0"
tokio = "1.32.0"
ipnet = "2.8.0"
anyhow = "1.0.69"
itertools = "0.11.0"
